add vortex gui to welcome page
ln-vortex/ln-vortex pull request #367
Opened 2022-10-01 19:02 UTC by suhailsaqan

2022-10-04 22:47 UTC, deregs commented
Just added a more updated screenshot in the readme that you could use here

2022-10-11 03:38 UTC, benthecarman requested changes
should update the image to be the one from the other PR

2022-10-11 03:38 UTC, benthecarman commented on website/src/pages/index.js
> +                                </p>
I think instead should have something like:

```html
<h2>Easy to use</h2>

<p>
 Vortex comes with an easy to use GUI that is usable as a desktop application or as web server.
 Vortex handles all the hard work and privacy is only a click away.
</p>

```

2022-10-12 18:12 UTC, benthecarman requested changes
Still need to update the image

2022-10-14 03:06 UTC, merged